apiVersion: v1
kind: Service
metadata:
  name: flask-weather-app-service
spec:
  selector:
    app: flask-weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
