name: Deploy Flask App

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URI: "<your-ecr-repository-uri>"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG

  deploy_to_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: SSH and Deploy to EC2 Instances
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP_1 }},${{ secrets.EC2_PUBLIC_IP_2 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ github.sha }}
            docker pull $REPOSITORY_URI:$IMAGE_TAG
            docker stop flask_app || true
            docker rm flask_app || true
            docker run -d -p 80:5000 --name flask_app \
              -e WEATHER_API_TOKEN=${{ secrets.WEATHER_API_TOKEN }} \
              $REPOSITORY_URI:$IMAGE_TAG